/**
 * Patrol — automated flagging of low-trust actions for moderator review (§21.8).
 *
 * A flag is generated by `evaluateAction` and persisted in `patrol_flags`. The
 * admin patrol feed (`/api/admin/patrol`) lists unresolved flags; moderators
 * can revert a single revision or rollback all of an actor's consecutive
 * edits to one entity.
 *
 * Auto-flag triggers (any of):
 *   - new_tier_semi_edit:  New-tier user edits a semi- or full-protected entity
 *   - new_tier_revert_burst: New-tier user performs >5 reverts in 10 min
 *   - negative_karma_delete_revert: raw-negative-karma user does delete/revert
 *   - mass_revert_popular: mass revert of a popular system
 *   - mod_override: moderator performed an override action
 */
import { and, desc, eq, gte, sql } from "drizzle-orm";
import { db } from "../db/index.js";
import { patrolFlags, revisions, users } from "../db/schema.js";
import {
  PATROL_REVERT_BURST_COUNT,
  PATROL_REVERT_BURST_WINDOW_MIN,
  type PatrolFlagReason,
  type TrustTier,
} from "@magnum/shared/constants";
import { tierFromKarma } from "./karma.js";
import { effectiveProtection, isModerator } from "./protection.js";
import { entityStats, entityProtection } from "../db/schema.js";

export interface FlagContext {
  revisionId: string;
  actorId: string | null;
  actorKarma: number;
  actorRole: string | null;
  targetType: string;
  targetId: string;
  action: string; // "create" | "update" | "delete" | "revert" | "assign" | "reassign"
}

function actorTier(actorKarma: number): TrustTier {
  return tierFromKarma(actorKarma);
}

/**
 * Inspect an action and write any applicable flag rows. Idempotent: if a
 * flag for this revision+reason already exists, it is left alone. Returns
 * the list of new flags created.
 */
export async function evaluateAction(ctx: FlagContext): Promise<PatrolFlagReason[]> {
  const flags: PatrolFlagReason[] = [];
  const tier = actorTier(ctx.actorKarma);
  const isNew = tier === "new";
  const isMod = isModerator(ctx.actorRole);
  const isRevert = ctx.action === "revert";
  const isDelete = ctx.action === "delete";

  // 1. New-tier user edits/reverts a semi- or full-protected entity.
  if (isNew && !isMod) {
    const prot = await computeProtectionFor(ctx.targetType, ctx.targetId);
    if (prot === "semi" || prot === "full") {
      flags.push("new_tier_semi_edit");
    }
  }

  // 2. New-tier revert burst.
  if (isNew && !isMod && isRevert) {
    const windowStart = new Date(
      Date.now() - PATROL_REVERT_BURST_WINDOW_MIN * 60 * 1000,
    );
    if (ctx.actorId) {
      const recent = await db
        .select({ count: sql<number>`count(*)::int` })
        .from(revisions)
        .where(
          and(
            eq(revisions.authorId, ctx.actorId),
            eq(revisions.action, "revert"),
            gte(revisions.createdAt, windowStart),
          ),
        );
      const count = Number(recent[0]?.count ?? 0);
      if (count > PATROL_REVERT_BURST_COUNT) {
        flags.push("new_tier_revert_burst");
      }
    }
  }

  // 3. Raw-negative-karma user does delete/revert.
  if (ctx.actorKarma < 0 && !isMod && (isDelete || isRevert)) {
    flags.push("negative_karma_delete_revert");
  }

  // 4. Mass revert of a popular system — heuristic: revert on a system with
  //    >20 net upvotes from a New-tier user.
  if (isNew && !isMod && isRevert && ctx.targetType === "system") {
    const popular = await db
      .select({ upvotes: entityStats.upvotes })
      .from(entityStats)
      .where(
        and(
          eq(entityStats.targetType, "system"),
          eq(entityStats.targetId, ctx.targetId),
        ),
      )
      .limit(1);
    if (Number(popular[0]?.upvotes ?? 0) > 20) {
      flags.push("mass_revert_popular");
    }
  }

  // 5. Mod override — log when a moderator reverses a prior decision.
  if (isMod && isRevert) {
    flags.push("mod_override");
  }

  // Persist (skip duplicates).
  for (const reason of flags) {
    await db
      .insert(patrolFlags)
      .values({ revisionId: ctx.revisionId, reason })
      .onConflictDoNothing();
  }
  return flags;
}

async function computeProtectionFor(
  targetType: string,
  targetId: string,
): Promise<"normal" | "semi" | "full"> {
  const [prot, stats] = await Promise.all([
    db
      .select()
      .from(entityProtection)
      .where(
        and(
          eq(entityProtection.targetType, targetType),
          eq(entityProtection.targetId, targetId),
        ),
      )
      .limit(1),
    db
      .select({ upvotes: entityStats.upvotes })
      .from(entityStats)
      .where(
        and(eq(entityStats.targetType, targetType), eq(entityStats.targetId, targetId)),
      )
      .limit(1),
  ]);
  // Child count is non-trivial for system vs trail; keep it simple here and
  // let `effectiveProtection` default to 0 children if absent. The route
  // layer will trigger a full refresh after writes anyway.
  return effectiveProtection({
    targetType: targetType as never,
    targetId,
    upvotes: Number(stats[0]?.upvotes ?? 0),
    children: 0,
    storedLevel: prot[0]?.level as "normal" | "semi" | "full" | undefined,
  });
}

/**
 * Mark a flag as resolved by a moderator.
 */
export async function resolveFlag(flagId: string, resolverId: string): Promise<void> {
  await db
    .update(patrolFlags)
    .set({ resolved: true, resolvedBy: resolverId, resolvedAt: new Date() })
    .where(eq(patrolFlags.id, flagId));
}

/**
 * List recent patrol flags with optional filters.
 */
export async function listPatrolFlags(opts: {
  reason?: PatrolFlagReason;
  userId?: string;
  resolved?: boolean;
  page: number;
  pageSize: number;
}): Promise<{ items: Array<Record<string, unknown>>; total: number }> {
  const page = Math.max(1, opts.page);
  const pageSize = Math.min(100, Math.max(1, opts.pageSize));
  const offset = (page - 1) * pageSize;

  const baseSelect = {
    id: patrolFlags.id,
    revision_id: patrolFlags.revisionId,
    reason: patrolFlags.reason,
    details: patrolFlags.details,
    resolved: patrolFlags.resolved,
    resolved_by: patrolFlags.resolvedBy,
    resolved_at: patrolFlags.resolvedAt,
    created_at: patrolFlags.createdAt,
    revision_target_type: revisions.targetType,
    revision_target_id: revisions.targetId,
    revision_action: revisions.action,
    revision_author_id: revisions.authorId,
    revision_summary: revisions.editSummary,
  } as const;

  // Build the where conditions for both the items query and the count.
  const conditions = [];
  if (opts.reason) conditions.push(eq(patrolFlags.reason, opts.reason));
  if (opts.resolved !== undefined) conditions.push(eq(patrolFlags.resolved, opts.resolved));
  if (opts.userId) conditions.push(eq(revisions.authorId, opts.userId));
  const where = conditions.length ? and(...conditions) : undefined;

  const [rows, totalRow] = await Promise.all([
    db
      .select(baseSelect)
      .from(patrolFlags)
      .leftJoin(revisions, eq(revisions.id, patrolFlags.revisionId))
      .where(where)
      .orderBy(desc(patrolFlags.createdAt))
      .limit(pageSize)
      .offset(offset),
    db
      .select({ count: sql<number>`count(*)::int` })
      .from(patrolFlags)
      .leftJoin(revisions, eq(revisions.id, patrolFlags.revisionId))
      .where(where),
  ]);

  return {
    items: rows as unknown as Array<Record<string, unknown>>,
    total: Number(totalRow[0]?.count ?? 0),
  };
}

/**
 * Rollback: revert all of an actor's consecutive revisions on one entity back
 * to the state before they started editing it. Used by the patrol UI to
 * reverse a single bad actor's burst in one click.
 */
export async function rollbackActorEdits(
  actorId: string,
  targetType: string,
  targetId: string,
  resolverId: string,
): Promise<{ reverted: number }> {
  const recent = await db
    .select()
    .from(revisions)
    .where(
      and(
        eq(revisions.authorId, actorId),
        eq(revisions.targetType, targetType),
        eq(revisions.targetId, targetId),
      ),
    )
    .orderBy(desc(revisions.createdAt));
  if (recent.length === 0) return { reverted: 0 };
  // Find the oldest consecutive edit by this actor.
  let cutoffIdx = 0;
  for (let i = 1; i < recent.length; i++) {
    if (recent[i]?.authorId !== actorId) break;
    cutoffIdx = i;
  }
  const toRevert = recent.slice(0, cutoffIdx + 1);
  // We write a marker revision for the rollback. The actual data revert
  // is the caller's responsibility (entity-specific). Here we just record
  // the audit trail.
  await db.insert(revisions).values({
    targetType,
    targetId,
    action: "revert",
    contributorName: "patrol-rollback",
    authorId: resolverId,
    editSummary: `Rollback of ${toRevert.length} edits by ${actorId}`,
    payloadBefore: { rolledBackRevisions: toRevert.map((r) => r.id) },
  });
  return { reverted: toRevert.length };
}

export async function lookupActorKarma(userId: string): Promise<number> {
  const rows = await db
    .select({ karma: users.trustScore })
    .from(users)
    .where(eq(users.id, userId))
    .limit(1);
  return Number(rows[0]?.karma ?? 0);
}
