-- trace_heatmap — cached tile-level trace density for the explore map overlay.
-- Stores counts at zoom 14; lower zooms aggregate up. Updated incrementally
-- on trace create/status-change and fully regenerated by the admin heatmap job.

CREATE TABLE "trace_heatmap" (
  "tile_x" integer NOT NULL,
  "tile_y" integer NOT NULL,
  "zoom" integer NOT NULL,
  "trace_count" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "trace_heatmap_zoom_tile_x_tile_y_pk" PRIMARY KEY("zoom","tile_x","tile_y")
);
